COMMON: &common
  CSRF_ENABLED: True
  SECRET_KEY: '622fa765fa110611a164164fa347e941687cb7711c4ad6f1017a448cdd4c8c64'
  DEBUG: True
  TESTING: True

DEVELOPMENT: &development
  <<: *common
  MONGODB_SETTINGS:
    DB: 'webstub'
    HOST: 'localhost'

PRODUCTION: &production
  <<: *common
  DEBUG: False
  TESTING: False
  MONGODB_SETTINGS:
    DB: 'webstub'
    HOST: 'localhost'
